name: medito
description: A meditation learning tool

# flutter clean && flutter build apk --release --no-tree-shake-icons
# flutter clean && flutter build appbundle --obfuscate --split-debug-info=./debug-info --target-platform android-arm,android-arm64,android-x64 --no-tree-shake-icons
# flutter clean && flutter build ios --no-tree-shake-icons
version: 3.1.14+30051

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.18
  audio_service: ^0.18.12
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_analytics: ^10.8.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.2.2
  flutter_markdown: ^0.6.18+3
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  health: ^11.0.0
  http: ^1.2.0
  image: ^4.1.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  package_info_plus: ^8.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  reorderables: ^0.6.0
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  sentry_flutter: ^7.16.1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  url_launcher: ^6.2.3
  flutter_flavor: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Add this line
  pigeon: ^13.1.2
  mocktail: ^1.0.2
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  assets:
    - assets/
    - .prod.env
    - .staging.env
    - assets/images/
  fonts:
    - family: Source Serif
      fonts:
        - asset: assets/fonts/source-serif/SourceSerif4-Regular.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Medium.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-SemiBold.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Bold.ttf
    - family: DM Mono
      fonts:
        - asset: assets/fonts/dm-mono/DMMono-Medium.ttf
        - asset: assets/fonts/dm-mono/DMMono-Regular.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm-sans/DMSans-SemiBold.ttf

  uses-material-design: true
