name: medito
description: A meditation learning tool

# flutter clean && flutter build apk --release --no-tree-shake-icons  --dart-define-from-file=../.prod.json
# flutter clean && flutter build appbundle --obfuscate --split-debug-info=./debug-info --target-platform android-arm,android-arm64,android-x64 --no-tree-shake-icons  --dart-define-from-file=../.prod.json
# flutter clean && flutter build ios --no-tree-shake-icons  --dart-define-from-file=../.prod.json
version: 3.2.1+30060

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.21
  audio_service: ^0.18.15
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.2.2
  flutter_markdown: ^0.6.18+3
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.4
  health: ^11.0.0
  http: ^1.2.0
  image: ^4.1.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.41
  package_info_plus: ^8.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  reorderables: ^0.6.0
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  sentry_flutter: ^8.9.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  url_launcher: ^6.2.3
  webview_flutter: ^4.9.0
  uuid: ^4.5.0
  hugeicons:
    hosted: https://onepub.dev/api/kdpxxpsdav/
    version: ^0.0.4
  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^10.0.2
  app_links: ^3.4.1
  supabase_flutter: ^2.0.0
  internet_connection_checker_plus: ^2.5.2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^13.1.2
  mocktail: ^1.0.2
  build_runner: ^2.4.13
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  mockito: ^5.4.4
  analyzer: ^5.13.0

flutter:
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Source Serif
      fonts:
        - asset: assets/fonts/source-serif/SourceSerif4-Regular.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Medium.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-SemiBold.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Bold.ttf
    - family: DM Mono
      fonts:
        - asset: assets/fonts/dm-mono/DMMono-Medium.ttf
        - asset: assets/fonts/dm-mono/DMMono-Regular.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm-sans/DMSans-SemiBold.ttf
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/dm-serif/DMSerifDisplay-Regular.ttf
        - asset: assets/fonts/dm-serif/DMSerifDisplay-Italic.ttf
    - family: Teachers
      fonts:
        - asset: assets/fonts/teachers/Teachers-Regular.ttf
        - asset: assets/fonts/teachers/Teachers-Bold.ttf
        - asset: assets/fonts/teachers/Teachers-Medium.ttf
        - asset: assets/fonts/teachers/Teachers-SemiBold.ttf
  uses-material-design: true
