name: Medito
description: A meditation learning tool

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.22+30022
environment:
  sdk: ">=2.18.0 <3.7.0-13.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^5.1.1
  auto_size_text: ^3.0.0-nullsafety.0
  back_button_interceptor: ^6.0.2
  cached_network_image: ^3.2.3
  connectivity: ^3.0.3
  device_info_plus: ^9.0.2
  dio: ^5.4.0
  email_validator: '^2.1.16'
  equatable: ^2.0.0
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  flutter_dotenv: ^5.0.2
  flutter_downloader: ^1.10.2
  flutter_html: ^3.0.0-alpha.2
  flutter_local_notifications: ^15.0.0
  flutter_markdown: ^0.6.7
  flutter_riverpod: ^2.4.10
  flutter_svg: ^1.1.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^6.5.5
  google_api_availability: ^5.0.0
  http: ^0.13.3
  image: ^4.0.17
  json_annotation: ^4.8.1
  marquee: ^2.2.3
  package_info_plus: ^4.0.2
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  permission_handler: ^11.2.0
  pin_code_fields: ^7.4.0
  reorderables: ^0.6.0
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.1
  sentry_flutter: ^7.16.0
  share: ^2.0.1
  share_plus: ^7.0.2
  shimmer: ^2.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  workmanager: ^0.5.2

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^16.0.5
  mocktail: ^0.3.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  dart_code_metrics: ^5.7.0
  #USAGE: dart run build_runner watch --delete-conflicting-outputs

flutter:
  assets:
    - assets/
    - .prod.env
    - .staging.env
    - assets/images/
  fonts:
    - family: Source Serif
      fonts:
        - asset: assets/fonts/source-serif/SourceSerif4-Regular.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Medium.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-SemiBold.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Bold.ttf
    - family: DM Mono
      fonts:
        - asset: assets/fonts/dm-mono/DMMono-Medium.ttf
        - asset: assets/fonts/dm-mono/DMMono-Regular.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm-sans/DMSans-SemiBold.ttf

  uses-material-design: true
